### ISSUE TITLE
great for this

### ISSUE THREAD

**Issue by tixo** [dosentmatter/rainbow-bash-prompt#1]
Nice Work, and can you provide a zsh prompt?

**Comment by dosentmatter** [comment]
Thanks. I really shouldn't be working on this because I'm busy with other stuff, but I started on it and couldn't stop.

Here you go:
https://github.com/dosentmatter/rainbow-zsh-prompt

The code is almost the same as the bash one but I didn't spend the time to clean things up using zsh specific features. I won't be cleaning it up for now. I tested it a little bit.

I rarely use zsh, so I'm not gonna use rainbow-zsh-prompt. You better use it! Create an issue if you find any problems.

Let me know I can close this issue.

**Comment by tixo** [comment]
Thanks for do this stuff and Of course you can close this issue .
